// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"net/http"
)

// Injectors from injector.go:

func NewApp() *http.Server {
	router := NewRouter()
	server := NewServer(router)
	return server
}
